### ISSUE TITLE
"make -j" Command Issue

### ISSUE THREAD

**Issue by FCPlech** [OpenHantek/openhantek#102]
When "make -j" command is used, the Linux Mint freezes. It was only possible when I used command "make -j4" instead of "make -j".

**Comment by davidgraeff** [comment]
Make will take all available CPU cores and a lot of memory will be acquired to compile as much as possible in parallel. If you compile on a raspberry pi, the system will freeze, a core i7 or amd ryzen you will barely notice anything. 
This is not a bug in the build system :)
