### ISSUE TITLE
Invalid inverted channel display

### ISSUE THREAD

**Issue by dendvz** [OpenHantek/openhantek#110]
@klemens , the "inverted" trace display https://github.com/OpenHantek/openhantek/commit/8737282c681667d9fd6e9c6ab9c585925c4bf995 shall __not__ touch channel offset, the right formula is:
```
   *(glIterator++) = invert * (*(dataIterator++) / gain) + offset;
```
(same for X-Y display)
Please notice the CH1 baseline at +1 div, while inverted channel is displayed as if it has offset of -1 div.
![inverted_channel](https://user-images.githubusercontent.com/11679699/34270737-46cbe9f8-e69a-11e7-9b6b-429e9e40fd76.png)

BTW, it would be great to interpret this "invertor" stuff as first step towards feature request #74.

**Comment by klemens** [comment]
You are right, inverting the offset doesn't make any sense. I submitted #111 to fix this.
