### ISSUE TITLE
firmware issue in current gitHub project

### ISSUE THREAD

**Issue by WaveLicker** [OpenHantek/openhantek#113]
Hi,
I have an issue when connecting my 6022BE with the current builded version. I have an error message saying "DSO-6022BE : Firmware upload failed". and a second message : A device was found but the firmware upload seems to have failed or connection could notbe established".

Now, if I leave connected my 6022BE and open a previous release (18.12.17). I have no issue and have my oscilloscope running. If I close that version , keep the USB cable connected to my laptop and then open the last release. It works perftectly. If I disconnect the USB cable the application close and if I open the application again: issue come back.
So I have to open older version first.

**Comment by davidgraeff** [comment]
Yes, you are right. The actual call to `UploadFirmware().startUpload` got accidentally removed in `main.cpp`.

**Comment by velteyn** [comment]
we solved starting program with sudo, after we was in Super User mode the problem evaporated ;)

**Comment by davidgraeff** [comment]
U need to install the udev rule. A GUI program running as root is never a good idea. The firmware upload and recognising the device immediately after is still buggy so I leave this report open for now.
