### ISSUE TITLE
6022BL - Square wave when measuring

### ISSUE THREAD

**Issue by dalva24** [OpenHantek/openhantek#124]
Greetings,

I have built the [latest commit](https://github.com/OpenHantek/openhantek/commit/db4f8ba0b7b2bcc9ee7f41c96b597cdda56acacc) on Ubuntu 16.04, following the steps in build.md

When I start measuring, both channel only show square wave, as can be seen in the screenshot (channel 1 shown):
![screenshot](https://user-images.githubusercontent.com/7037014/34332485-950a20be-e963-11e7-99f2-63e67b2f40b4.png)

I tried grounding the probe tip, attaching the probe tip to the calibration output, even removing the probe altogether, but the waveform stays the same.

I have tried using the scope in windows using the Hantek software before and it works, so the hardware is supposedly fine.

Thanks

**Comment by davidgraeff** [comment]
I can confirm this. I don't know if it is because of the firmware that we send to the 6022 or if a recent change is causing this. Needs to be investigated.

**Comment by davidgraeff** [comment]
It is not a recent change. This behaviour is since first adding support for 6022. I guess the firmware we use does only work for 6022BE and not BL

**Comment by dalva24** [comment]
I'm unable to build on Windows, so I can't try flashing using original firmware then start OpenHantek as you suggested. Is it possible to extract the firmware from the official Windows BL driver?

**Comment by eagafonov** [comment]
I confirm: the new firmware works on 6022BL. 
Tested on Debian "Jessie".
