### ISSUE TITLE
Add slider on commands section

### ISSUE THREAD

**Issue by velteyn** [OpenHantek/openhantek#126]
Hello,
we are using a small Acer Aspire One here and its monitor is very small (11'') .
It would be very useful to have a vertical slider on the command bar on the right so to be able to access all the bottom commands. Also is it possible to resize the measure screen ? The exact monitor height can be deduced by the image we attach.

Thank you
![schermata da 2017-12-25 17-42-28](https://user-images.githubusercontent.com/1019294/34352602-e4d24494-ea23-11e7-9f84-61ed1c317197.png)

**Comment by dendvz** [comment]
@velteyn Can you use tab layout of dock windows? Please refer to #89, I've managed to shrink window to 800x600.

**Comment by davidgraeff** [comment]
We are missing a features section in the readme. It need to be mentioned somewhere that tabs are possible I think. A vertical slider is not possible. The scope view has a minimum required size as well but as @dendvz said already, 800*600 is possible.

**Comment by velteyn** [comment]
ok thanks
