### ISSUE TITLE
Cmake met problem in windows

### ISSUE THREAD

**Issue by mike9755** [OpenHantek/openhantek#134]
I got wrong message when using cmake to congifure win-project, detail as picture, can someone help me on this? thank you very much.
![cmake](https://user-images.githubusercontent.com/5673534/34469020-8e505ee4-ef50-11e7-9a62-ec01d07fd47c.png)

**Comment by davidgraeff** [comment]
This is not an error, it is only a warning message. It just tells you that you can't compile the firmware extractor on windows. I will remove the warning for windows users.

**Comment by mike9755** [comment]
Dear David 
I download the latest version code, and use cmake to build the project for windows, but still got an error, please help me , thank you.
![image](https://user-images.githubusercontent.com/5673534/34489286-b865725c-f016-11e7-8f29-6e4a4062665a.png)

**Comment by mike9755** [comment]
Dear David
I have build the VS project successfully, but now I meet a new problem about build the project in visual studio as below picture.
![image](https://user-images.githubusercontent.com/5673534/34491554-de0faaa6-f01e-11e7-9508-be4a31a29d4b.png)
