### ISSUE TITLE
Build error in visual studio

### ISSUE THREAD

**Issue by mike9755** [OpenHantek/openhantek#135]
I got 4 error messages when try to build this project without any modification,detailed information as picture,please help me, thank you very much.

![2018-01-03 11 37 19](https://user-images.githubusercontent.com/5673534/34508455-7a11b68c-f07a-11e7-8042-9ba647f2440d.png)

**Comment by davidgraeff** [comment]
Which VS version? We have a continous integration solution with a windows visual studio 2015 installation, which checks every commit and pull request. Here it seems that `VERSION` is not defined. This comes from the cmake buildsystem in the file CPackInfos.cmake:
`set(CPACK_PACKAGE_VERSION "${DATE_VERSION}_${VCS_REVISION}")`
and in openhantek/CMakeLists.txt:
`add_definitions(-DVERSION="${CPACK_PACKAGE_VERSION}")`

**Comment by mike9755** [comment]
Dear David
I used vs17 community to build th is project got that 4 errors , I reinstall a vs15 to build today but failed again with some other errors. thanks.

**Comment by marktoml** [comment]
I have been looking at getting it going with VS17 community edition and with CMake, if I get a chance I’ll focus on it this weekend.

Mark
P.S. I am assuming it builds well elsewhere 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by davidgraeff** [comment]
VS2017 can work with cmake projects natively. This might indeed work different and produce errors which do not occur with the "old school" way of generating VS projects with the cmake executable first.
Try with defining VERSION in main.cpp like this:
`#define VERSION "TEST"` and see if it works.

**Comment by mike9755** [comment]
I'm completely confused now, I got 3700+ errors now, there three kinds of errors "LNK2001" "LNK2019" and "LNK1120", all them were showed in the picture, my cmake version is 3.10.1, QT version is 5.4.1
![image 1](https://user-images.githubusercontent.com/5673534/34648740-e2fdf468-f3da-11e7-9cd8-657fbf67c65d.png)

**Comment by davidgraeff** [comment]
@mike9755 I compiles fine now though. The second step, the linking, fails for you. It looks like VS doesn't find the Qt libraries.

On Windows you usually have to set the Qt header path and Qt library path manually in the cmake GUI. I don't know how to do that with the native cmake support in VS.

**Comment by mike9755** [comment]
Dear David
My cmake GUI screen as below, please help me how to set the Qt header path manually, thanks.

![image 2](https://user-images.githubusercontent.com/5673534/34650229-7fdd509a-f3f8-11e7-8434-062593c201f3.png)

**Comment by davidgraeff** [comment]
Ah ok. You are compiling with the visual studio compiler but you are linking to the mingw Qt libraries. They are not compatible because Microsoft introduced multiple linking standards over the years. You need to install a compatible Qt with the VS version that you have.

**Comment by mike9755** [comment]
You are right, life is really hard on windows like you said, I've fixed most question now, I resinstalled a VS2015 and installed "qt-opensource-windows-x86-msvc2015-5.8.0.exe" which suit to VS, most errors have gone now, but the default fftw package is also mingw compiled, I find I can't fix this problem, can you kindly send me your windows compatible fftw package?my email is "mike97555@gmail.com",  or give new ideals to fix this problem, thank you very much
![image 4](https://user-images.githubusercontent.com/5673534/34732703-f940db1a-f5a0-11e7-95bf-262c5401aa65.png)
![image 3](https://user-images.githubusercontent.com/5673534/34732735-09ca420a-f5a1-11e7-9727-5e50a2348336.png)

**Comment by marktoml** [comment]
That is about where I stalled last session 😊
I will look into it again as soon as I get a break, but if someone has this working … clue me in.

Mark

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by davidgraeff** [comment]
It starts with a selection screen, always. Try to start in debug and see if it maybe crashes for you (which I actually don't believe). And make sure, you don't use the "Start" button of visual studio while "ALL_BUILD" is still the current project. You need to select "OpenHantek" as project first. CMake is really not made for VS unfortunately.

**Comment by davidgraeff** [comment]
Because this is not an issue of OpenHantek I close this report now :)

**Comment by mike9755** [comment]
Ok, thank you for your help
