### ISSUE TITLE
Unable to install - make command fails

### ISSUE THREAD

**Issue by newtonis** [OpenHantek/openhantek#17]
It outputs 
``newtonis@newtonis-B85M-DS3H:~/OpenHantek-openhantek-48d6e64$ make
``
``
gcc -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Iopenhantek/src -Iopenhantek/src/hantek -I. -o extractfw.o openhantek-extractfw/extractfw.c
openhantek-extractfw/extractfw.c:31:17: fatal error: bfd.h: No such file or directory
compilation terminated.
Makefile:383: recipe for target 'extractfw.o' failed
make: *** [extractfw.o] Error 1
``

I installed all the dependencies listed with no errors. I'm running Ubuntu GNOME 15.10

**Comment by UncleRus** [comment]
May be `apt-get install binutils-dev`
