### ISSUE TITLE
Use sigrok decoders

### ISSUE THREAD

**Issue by phmarek** [OpenHantek/openhantek#175]
The sister project "Sigrok" (with frontend "Pulseview") can convert analog into digital signals, and then have them decoded via python scripts.
Examples are RS232, SPDIF, DCF77, and lots more.

It would be great if the OpenHantek would use the same interface (and, by implication, could reuse the same set of decode scripts!) to provide an easy way to analyze some signal path.

Please see https://sigrok.org/gitweb/?p=libsigrokdecode.git;a=summary for the decoders; I hope that the implementation of attaching these can be lifted from PV resp. sigrok in some way.

**Comment by davidgraeff** [comment]
I do not understand this feature request. If you want a logic analyzer, use https://www.saleae.com/. Works on all OpenHantek supported operating systems. Alternatively use Sigrok Pulseview. But OpenHantek is in no way a logic analyzer.
Even if the post processing would pass the data to `libsigrokdecode`, what exactly should happen to the received decoded signal? There is no graphical interface to support this idea.

Of course if anybody is highly interested, he/she can contribute to this project.
