### ISSUE TITLE
Multiple windows for small displays

### ISSUE THREAD

**Issue by phmarek** [OpenHantek/openhantek#179]
For small displays (eg. 800x600) it might make sense to split the GUI into multiple X11 windows.

Some toolkits allow to tear menus off the main window, and some of the settings in OH can already be hidden; perhaps some similar mechanism can be used here.

**Comment by davidgraeff** [comment]
Ehm, this is done already. OpenHantek uses dock windows and they can be dragged off the window and manifest into own windows. This works on all supported operating systems

**Comment by phmarek** [comment]
Not yet for the new measurements dock (#177); perhaps the zoomed window might be split off in the same way?
