### ISSUE TITLE
Why doesn't upload compiled binaries to your homepage? Compiling suxx ^^

### ISSUE THREAD

**Issue by Kulturnilpferd** [OpenHantek/openhantek#190]
Please make for mac and windows users a compiled binary! I have a Windows and a Mac and on both machines I'm too stupid to use this shitty cmake or qt5. Either import to Visual Studio fails. You have a very nice homepage (openhantek.org) and then you link everyone to github to compile it? Why you don't compile the binarys by yourself and upload them to your webserver so that people who never compile things can download a zip and run simply the exe or app from it. I hate this fuckin compiler! On windows on linux on mac EVERYWHERE!!!! 
Beside that, the install instructions are very short and doesn't help to compile it either!
I am able to change things by reverse engineering could program things in c# or c++ on windows or do things with a hexeditor but not able to fuckin compile this... Ridiculous!!! :/

**Comment by davidgraeff** [comment]
Please respect community guidelines and general code of conduct, you are using disrespectful phrases. Your issue does not seem to be helpful and you are not reporting a bug. This be closed now. If you thing, that the build instructions need to be refined (" the install instructions are very short"), please open another issue.
