### ISSUE TITLE
Waveform doesn't fill screen when timebase > 5msec

### ISSUE THREAD

**Issue by richardklingler** [OpenHantek/openhantek#193]
When timebase is chosen greater than 5msec, the waveform doesn't fill the entire screen.
On macOS 10.12.6 and Debian 9 the displayed waveform is shrunk with each step above 5msec...

See screen: https://pasteboard.co/HavK19R.png

**Comment by dendvz** [comment]
Functions as designed - it is a limitation of 6022Bx. The lowest sample rate is 200kS/s, which turns into full record length of ~41ms.

**Comment by richardklingler** [comment]
Okay...thought something like that (o;
