### ISSUE TITLE
Clicking on bottom/right resize corner enlarges windows immediately

### ISSUE THREAD

**Issue by richardklingler** [OpenHantek/openhantek#194]
Click on the bottom right corner in the window causes it to enlarge immediately whereas the mouse pointer stays at around 60% right, 60% down.

See screenshot: https://pasteboard.co/HavN1gY.png

**Comment by davidgraeff** [comment]
This might be because your Qt version is not new enough and causes issues in relation to your super-high dpi desktop. We cannot influence this behavior from within OpenHantek unfortunately. If this does not happen with other Qt based applications, please report back. Thanks.
