### ISSUE TITLE
When started from shell, program doesn't terminate on Debian when closing application

### ISSUE THREAD

**Issue by richardklingler** [OpenHantek/openhantek#195]
The shell isn't released when OpenHantek is terminated on Debian 9.
You have to do a Ctrl-C to quit the application.

**Comment by davidgraeff** [comment]
Can you please test towards this specific issue with the openhantek2 branch?

**Comment by richardklingler** [comment]
cmake fails on Debian 9:

klingler@debian:/home2/Develop/openhantek/build$ cmake ../
-- Version: openhantek2/3490680
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:26 (find_package):
  Could not find a package configuration file provided by "Qt53DCore" with
  any of the following names:

    Qt53DCoreConfig.cmake
    qt53dcore-config.cmake

  Add the installation prefix of "Qt53DCore" to CMAKE_PREFIX_PATH or set
  "Qt53DCore_DIR" to a directory containing one of the above files.  If
  "Qt53DCore" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  openhantek/CMakeLists.txt:3 (find_package)

**Comment by davidgraeff** [comment]
Yes, the dependencies have changed. You need to install the qt package that provides Qt3d.

**Comment by richardklingler** [comment]
No Qt-5.8 yet on Debian 9 (o;

CMake Error at openhantek/CMakeLists.txt:13 (message):
  Minimum supported Qt5 version is 5.8.0!

**Comment by davidgraeff** [comment]
True. It's debian. qt3D is the perfect match for OH to abstract away GPU shaders. Released with Qt 5.7 it only got stable with Qt 5.8 though :/

**Comment by wom-bat** [comment]
For what it's worth, I can build and run OpenHantek on Debian sid without these issues.

**Comment by uunicorn** [comment]
I have the same problem. Looks like a double-free issue.

**Comment by ikolinahr** [comment]
My apologies but I am new here. I just tried building openhantek2 and encountered the same error about Qt53DCore discussed in this thread. I am running openhantek 'master' just fine on Ubuntu 18.04, and have installed the package "qml-module-qt3d" suggested above, but the cmake error persists. What am I missing?
