### ISSUE TITLE
Marker time display wrong

### ISSUE THREAD

**Issue by richardklingler** [OpenHantek/openhantek#197]
Channel 1 shows a 1kHz sine wave from a HP 8904A...

Markers placed a complete sine wave apart...
Info screen shows correctly 1kHz, but marker time difference is displayed as 100msec...
The 100msec stay the same when changing the time base...

See screenshot: https://pasteboard.co/Haw2PG9z.png

**Comment by dendvz** [comment]
Yes, that looks incorrect. Marker 1 position should be 1ms, not 100ms. Will retest the latest tip of the master branch.
