### ISSUE TITLE
[Doubt] - Opening the Project on QTCreator

### ISSUE THREAD

**Issue by vlovini** [OpenHantek/openhantek#203]
Good afternoon!

First of all, congratulation on the development of this open source project! 

I'm trying to open the project on the QTCreator IDE, but the only thing I could open was the files themselves, not the project at all, where I want to understand the project structure.

Is it possible to provide the .pro file for us to open the project? Is there another way that I'm missing that I could have done before to solve my "problem"?

Note: I complied the project without aTny problems on Ubuntu 16.04 LTS.

Thanks a lot!

Best regards,
Vinícius Lora

**Comment by davidgraeff** [comment]
http://doc.qt.io/qtcreator/creator-project-cmake.html

QtCreator version 4.0 and up support cmake projects natively :)
