### ISSUE TITLE
Need versioning policy

### ISSUE THREAD

**Issue by Vascom** [OpenHantek/openhantek#210]
Where I can found current version of openhantek?
If it not exist what kind of versioning do you plan use for OpenHantek?
It will be tagget as release on github?

**Comment by davidgraeff** [comment]
As soon as the automatic package generation works, the next openhantek release can be tagged, yes.

**Comment by Vascom** [comment]
What type of versioning you plan use?
For example 1.0.0 or 18.03 or other?

**Comment by davidgraeff** [comment]
Because it is a rolling release software, it would be like it is defined right now:
https://github.com/OpenHantek/openhantek/blob/52622ac973ce552c5ee5a2ecd7de6443c5026fa3/cmake/CPackInfos.cmake#L86

So yes, it is the date underscore githash.

**Comment by Vascom** [comment]
OK. Thanks.
