### ISSUE TITLE
Build / cmake  error on Mint 18.03

### ISSUE THREAD

**Issue by schweini** [OpenHantek/openhantek#212]
After installing the listed prerequisites on Mint 18.03, running "cmake ../" gives the following error:

CMake Error at CMakeLists.txt:50 (find_package):
  By not providing "Findlibusb.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "libusb", but
  CMake did not find one.

  Could not find a package configuration file provided by "libusb" with any
  of the following names:

    libusbConfig.cmake
    libusb-config.cmake

  Add the installation prefix of "libusb" to CMAKE_PREFIX_PATH or set
  "libusb_DIR" to a directory containing one of the above files.  If "libusb"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by Vascom** [comment]
Maybe you forgot install libusb-1.0-0-dev?

**Comment by schweini** [comment]
Weird. No - I did install it, ajust like the instructions said. 

I rebooted, and now make is chugging along.

Thanks, anyhow!
