### ISSUE TITLE
Integrate firmware loading

### ISSUE THREAD

**Issue by davidgraeff** [OpenHantek/openhantek#22]
At the moment we need a special udev file which instructs an external program (fxload) to load the firmware to a DSO. The actual procedure and code is very simple and the uploading should be done by OpenHantek instead.

Reference: https://github.com/libusb/libusb/blob/master/examples/fxload.c (ezusb.h, ezusb.c are the interesting files that we may use directly, GPL licensed)

**Comment by 3esmit** [comment]
This enhancement will provide ARM (raspberry pi/raspbian) compatibility to OpenHantek?

**Comment by davidgraeff** [comment]
Isn't fxload also available for arm architectures? Basically I only want to avoid depending on an external tool just because of 600 lines of c code that can also be integrated.

**Comment by 3esmit** [comment]
Yes, but the .sys hantek delivers are for x86 and 64 arch, none for arm. Or can I use x86 to extract .hex and use this hex in arm linux (raspbian, for example)?

**Comment by davidgraeff** [comment]
Exactly. The firmware does not depend on the host system and is always the same. You may use the files that are located in firmware/.
