### ISSUE TITLE
recommendations for tablets or other devices to run this software on.

### ISSUE THREAD

**Issue by lee3836hester** [OpenHantek/openhantek#271]
For a person of limited means, what would be a minimally sufficient piece of hardware to get good functionality?

**Comment by LameLefty** [comment]
I can't speak to tablets, but as I've recently determined in #258, a Raspberry Pi 3 (or 3 Plus) will run OpenHantek perfectly. That's currently about $35 for the Pi, $10 for a PSU, $10 for a microSD card, $10 for a case,  plus whatever you choose to use for a keyboard, monitor and mouse.  An even less expensive RPi Zero W will also "work," but performance is frankly too sluggish to make it worthwhile. Spend $25 more for something usuable.

**Comment by davidgraeff** [comment]
Perfect answer. Minimum requirements are probably about 500mb ram, OpenGL 3 or OpenGL es 2 capable and around 1ghz cpu
