### ISSUE TITLE
Could NOT find libusb (missing: LIBUSB_INCLUDE_DIR)

### ISSUE THREAD

**Issue by MinimotoMusashi** [OpenHantek/openhantek#283]
Getting failure to make due to missing LIBUSB, I've installed it.
Has anyone else found a remedy for this issue?
OS: Centos 7

**Comment by Vascom** [comment]
You can install openhantek from rpmfusion repo.
Also in it spec-file present all build dependencies.

**Comment by MinmotoMusashi** [comment]
Thanks buddy.
Enabled rpmfusion repo and I've got it going now.
