### ISSUE TITLE
cursors in single mode

### ISSUE THREAD

**Issue by hackermagnet** [OpenHantek/openhantek#295]
I use the latesst version of OpenHantek on OS X 10.13.6 with a Hantek 6022BE.
I cannot see the cursors to measure time and voltage in single mode.
Is this normal?

**Comment by Ho-Ro** [comment]
No, at least not with my build.
![Cursor_Single_Mode](https://user-images.githubusercontent.com/12542359/58370931-99e88b80-7f0c-11e9-8525-da82cf22f495.png)
Please provide more detailed info.

**Comment by hackermagnet** [comment]
It seems to work fine with the releases from your link. I downloaded the source code and built it for OS X. Thank you!
There is a bit lag when I drag the cursors but it's not a big issue.
