### ISSUE TITLE
Error in Windows version OpenGL

### ISSUE THREAD

**Issue by pldestefa** [OpenHantek/openhantek#296]
Hi, I have the following error that I attach in the images, I am not a professional programmer, I do what I can, do you think I can solve it?

Thank you!
![Pantalla1](https://user-images.githubusercontent.com/51173367/58580901-8f880380-8224-11e9-9dc0-7eae1d457d7e.JPG)
![Pantalla2](https://user-images.githubusercontent.com/51173367/58580914-9a429880-8224-11e9-92fb-7f29a096271f.JPG)

**Comment by Ho-Ro** [comment]
Hi, you could try to start your openhantek with "openhantek --useGLES", see also #221. Or instead of using the unmaintained openhantek you can give my actively supported fork a try: https://github.com/OpenHantek/OpenHantek6022

**Comment by pldestefa** [comment]
Ho-Ro, thank you very much!  With the command line it worked.  I will also try the other version that you recommended me.
