### ISSUE TITLE
Refresh Button gone?

### ISSUE THREAD

**Issue by a-n-d-i** [OpenHantek/openhantek#335]
Hi,
the doc refers a refresh button on page 11 but I can't find it in the GUI. Is this a bug or has it moved? I'd really like some function to reset the single trigger. (3.3.0, downloaded today.

And
![Screenshot from 2022-06-04 16-35-52](https://user-images.githubusercontent.com/6292768/172007667-7a305bc4-89ad-41dc-8c51-28478e063438.png)

**Comment by Ho-Ro** [comment]
The  refresh button is only needed and visible in "Roll" trigger mode. In "Single" mode just use SPACE or "S".

**Comment by a-n-d-i** [comment]
sorry, will post there. Seems to be an issue if you start without an existing config, I'll explain there...
