### ISSUE TITLE
Decoding CAN and LIN

### ISSUE THREAD

**Issue by eried** [OpenHantek/openhantek#336]
Hi, is there any plan to include decoding of protocols? something like PicoScope does?

**Comment by eried** [comment]
Just because the limits as digital analyzer mode (supported by sigrok) is 5V and I want to read a 12V CAN :) so I am trying to decide on which scope to order.

thanks for the answer

**Comment by Ho-Ro** [comment]
> and I want to read a 12V CAN :)
It's always a good idea to use a transceiver to convert CAN to digital values - because communication in the automotive or industrial sector can involve strong voltage spikes. This one is simple and robust:
https://www.nxp.com/docs/en/data-sheet/PCA82C251.pdf
The same applies to LIN.
