### ISSUE TITLE
DSO5000P support ?

### ISSUE THREAD

**Issue by mjscosta** [OpenHantek/openhantek#36]
Hi, this is more of a question then an issue. 
Can the OpenHantek interact with the DSO5000P, since the default app is windows only, I would like to use linux with the scope, and perform captures and store in the pc ...

Thanks,
BC,mc

**Comment by cogwheel** [comment]
I haven't had any luck connecting to the DSO5072P

**Comment by AdrianBan** [comment]
Hi,

I was trying also to connect this Oscilloscope to Linux, even I've changed the udev rules and added the device there.
It's creating a Ethernet device on my pc.

Kind regards,
Adrian
