### ISSUE TITLE
Cannot compile without cloning

### ISSUE THREAD

**Issue by shalomcrown** [OpenHantek/openhantek#39]
If I just download the source code and try to compile (32-bit Ubuntu 16.04), cmake fails with the output below.

The downloadable source code is not a git repository, and you disallow cloning - which makes it difficult to overcome this problem.

If I create a git repository in the source directory, this solves the problem.

`
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
CMake Error at cmake/CPackInfos.cmake:28 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  CMakeLists.txt:30 (include)

CMake Error at cmake/CPackInfos.cmake:29 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  CMakeLists.txt:30 (include)

CMake Error at cmake/CPackInfos.cmake:30 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  CMakeLists.txt:30 (include)

CMake Error at cmake/CPackInfos.cmake:31 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  CMakeLists.txt:30 (include)

CMake Error at cmake/CPackInfos.cmake:32 (list):
  list GET given empty list
Call Stack (most recent call first):
  CMakeLists.txt:30 (include)

-- Configuring incomplete, errors occurred!
See also "/home/shalom/build/openhantek-untagged-de67b19b854308c333b9/build/CMakeFiles/CMakeOutput.log".
See also "/home/shalom/build/openhantek-untagged-de67b19b854308c333b9/build/CMakeFiles/CMakeError.log".
`

**Comment by davidgraeff** [comment]
fixed now
