### ISSUE TITLE
Cmake REPLACE Error (Mint 18 -- 16.04)

### ISSUE THREAD

**Issue by krakenrad** [OpenHantek/openhantek#41]
--------------------------------------------------------------------------------------------------------------------------------
Can any of the project developers test to see if openhantek can compile on a recent Ubuntu distro? I get a REPLACE error when trying to install it on Ubuntu 15.04, 15.10, 16.04.
--------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------
These instructions don't work:
--------------------------------------------------------------------------------------------------------------------------------
    apt-get install cmake qttools5-dev-tools libfftw3-dev binutils-dev libusb-1.0-0-dev

After you've installed the requirements either run cmake-gui or run the following commands inside the directory of this package:

    mkdir build
    cd build
    cmake ../
    make -j4 (for 4 concurrent compile jobs)
    make install (optional, for installing only)

Hi,
--------------------------------------------------------------------------------------------------------------------------------
Using Linux Mint 18 on x86 64. I needed to install qtbase5-dev and libqt5opengl5-dev to fix the first couple of errors I got.
--------------------------------------------------------------------------------------------------------------------------------
Now I get this (CMakeError.log posted at bottom of post.):
--------------------------------------------------------------------------------------------------------------------------------
$ cmake ../
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found libusb: /usr/lib/x86_64-linux-gnu/libusb-1.0.so  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found FFTW: /usr/lib/x86_64-linux-gnu/libfftw3.so  
CMake Error at cmake/CPackInfos.cmake:28 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  CMakeLists.txt:30 (include)

CMake Error at cmake/CPackInfos.cmake:29 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  CMakeLists.txt:30 (include)

CMake Error at cmake/CPackInfos.cmake:30 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  CMakeLists.txt:30 (include)

CMake Error at cmake/CPackInfos.cmake:31 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  CMakeLists.txt:30 (include)

CMake Error at cmake/CPackInfos.cmake:32 (list):
  list GET given empty list
Call Stack (most recent call first):
  CMakeLists.txt:30 (include)

-- Configuring incomplete, errors occurred!
See also "/home/jam/HantekBuild/openhantek-master/build/CMakeFiles/CMakeOutput.log".
See also "/home/jam/HantekBuild/openhantek-master/build/CMakeFiles/CMakeError.log".

--------------------------------------------------------------------------------------------------------------------
CMakeError.log:
--------------------------------------------------------------------------------------------------------------------
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/jam/HantekBuild/openhantek-master/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_6a05a/fast"
/usr/bin/make -f CMakeFiles/cmTC_6a05a.dir/build.make CMakeFiles/cmTC_6a05a.dir/build
make[1]: Entering directory '/home/jam/HantekBuild/openhantek-master/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_6a05a.dir/CheckSymbolExists.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_6a05a.dir/CheckSymbolExists.c.o   -c /home/jam/HantekBuild/openhantek-master/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_6a05a
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_6a05a.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_6a05a.dir/CheckSymbolExists.c.o  -o cmTC_6a05a -rdynamic 
CMakeFiles/cmTC_6a05a.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_6a05a.dir/build.make:97: recipe for target 'cmTC_6a05a' failed
make[1]: *** [cmTC_6a05a] Error 1
make[1]: Leaving directory '/home/jam/HantekBuild/openhantek-master/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_6a05a/fast' failed
make: *** [cmTC_6a05a/fast] Error 2

File /home/jam/HantekBuild/openhantek-master/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/jam/HantekBuild/openhantek-master/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_15985/fast"
/usr/bin/make -f CMakeFiles/cmTC_15985.dir/build.make CMakeFiles/cmTC_15985.dir/build
make[1]: Entering directory '/home/jam/HantekBuild/openhantek-master/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_15985.dir/CheckFunctionExists.c.o
/usr/bin/cc    -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_15985.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_15985
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_15985.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_15985.dir/CheckFunctionExists.c.o  -o cmTC_15985 -rdynamic -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_15985.dir/build.make:97: recipe for target 'cmTC_15985' failed
make[1]: *** [cmTC_15985] Error 1
make[1]: Leaving directory '/home/jam/HantekBuild/openhantek-master/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_15985/fast' failed
make: *** [cmTC_15985/fast] Error 2

**Comment by saogalde** [comment]
This really looks like this issue: https://github.com/OpenHantek/openhantek/issues/39 , although you don't have the two lines with the git error. Anyway, it can be useful.

**Comment by davidgraeff** [comment]
fixed now

**Comment by rahul-c54** [comment]
> fixed now

can you tell me how to fix it?
