### ISSUE TITLE
make install error: multiple definition

### ISSUE THREAD

**Issue by linpus** [OpenHantek/openhantek#44]
Hi, 
I use Linux Mint 17. 
When cmake-gui finished (with no error) i tried make install but got error:

$ make install
Scanning dependencies of target OpenHantek_automoc
[  4%] Automatic moc, uic and rcc for target OpenHantek
Generating moc_colorbox.cpp
Generating moc_configdialog.cpp
Generating moc_configpages.cpp
Generating moc_dataanalyzer.cpp
Generating moc_dockwindows.cpp
Generating moc_dsocontrol.cpp
Generating moc_dsowidget.cpp
Generating moc_exporter.cpp
Generating moc_glgenerator.cpp
Generating moc_glscope.cpp
Generating moc_control.cpp
Generating moc_device.cpp
Generating moc_levelslider.cpp
Generating moc_openhantek.cpp
Generating moc_settings.cpp
Generating moc_sispinbox.cpp
[  4%] Built target OpenHantek_automoc
Scanning dependencies of target OpenHantek
[  8%] Building CXX object openhantek/CMakeFiles/OpenHantek.dir/src/colorbox.cpp.o
[ 12%] Building CXX object openhantek/CMakeFiles/OpenHantek.dir/src/hantek/control.cpp.o
[ 16%] Building CXX object openhantek/CMakeFiles/OpenHantek.dir/src/hantek/device.cpp.o
[ 20%] Building CXX object openhantek/CMakeFiles/OpenHantek.dir/src/hantek/types.cpp.o
[ 25%] Building CXX object openhantek/CMakeFiles/OpenHantek.dir/src/dso.cpp.o
[ 29%] Building CXX object openhantek/CMakeFiles/OpenHantek.dir/src/settings.cpp.o
[ 33%] Building CXX object openhantek/CMakeFiles/OpenHantek.dir/src/helper.cpp.o
[ 37%] Building CXX object openhantek/CMakeFiles/OpenHantek.dir/src/levelslider.cpp.o
[ 41%] Building CXX object openhantek/CMakeFiles/OpenHantek.dir/src/main.cpp.o
[ 45%] Building CXX object openhantek/CMakeFiles/OpenHantek.dir/src/glscope.cpp.o
[ 50%] Building CXX object openhantek/CMakeFiles/OpenHantek.dir/src/dockwindows.cpp.o
[ 54%] Building CXX object openhantek/CMakeFiles/OpenHantek.dir/src/configdialog.cpp.o
[ 58%] Building CXX object openhantek/CMakeFiles/OpenHantek.dir/src/exporter.cpp.o
[ 62%] Building CXX object openhantek/CMakeFiles/OpenHantek.dir/src/glgenerator.cpp.o
[ 66%] Building CXX object openhantek/CMakeFiles/OpenHantek.dir/src/sispinbox.cpp.o
[ 70%] Building CXX object openhantek/CMakeFiles/OpenHantek.dir/src/configpages.cpp.o
[ 75%] Building CXX object openhantek/CMakeFiles/OpenHantek.dir/src/openhantek.cpp.o
[ 79%] Building CXX object openhantek/CMakeFiles/OpenHantek.dir/src/dataanalyzer.cpp.o
[ 83%] Building CXX object openhantek/CMakeFiles/OpenHantek.dir/src/dsocontrol.cpp.o
[ 87%] Building CXX object openhantek/CMakeFiles/OpenHantek.dir/src/dsowidget.cpp.o
[ 91%] Building CXX object openhantek/CMakeFiles/OpenHantek.dir/OpenHantek_automoc.cpp.o
[ 95%] Building CXX object openhantek/CMakeFiles/OpenHantek.dir/qrc_configdialog.cpp.o
[100%] Building CXX object openhantek/CMakeFiles/OpenHantek.dir/qrc_application.cpp.o
Linking CXX executable OpenHantek
CMakeFiles/OpenHantek.dir/qrc_application.cpp.o: In function `qInitResources()':
/home/mors/openhantek/build/openhantek/qrc_application.cpp:1131: multiple definition of `qInitResources()'
CMakeFiles/OpenHantek.dir/qrc_configdialog.cpp.o:/home/mors/openhantek/build/openhantek/qrc_configdialog.cpp:843: first defined here
CMakeFiles/OpenHantek.dir/qrc_application.cpp.o: In function `qCleanupResources()':
/home/mors/openhantek/build/openhantek/qrc_application.cpp:1140: multiple definition of `qCleanupResources()'
CMakeFiles/OpenHantek.dir/qrc_configdialog.cpp.o:/home/mors/openhantek/build/openhantek/qrc_configdialog.cpp:852: first defined here
CMakeFiles/OpenHantek.dir/src/main.cpp.o: In function `main':
/home/mors/openhantek/openhantek/src/main.cpp:37: undefined reference to `qInitResources_application()'
collect2: error: ld returned 1 exit status
make[2]: *** [openhantek/OpenHantek] Error 1
make[1]: *** [openhantek/CMakeFiles/OpenHantek.dir/all] Error 2
make: *** [all] Error 2

I have qt4 and qt5 installed together. Maybe problem in this?

Can anyone help me with it?
Thanks!

**Comment by davidgraeff** [comment]
Yes that is the problem. The qt libraries are linked twice. Nowadays there should be no reason to keep Qt4 anymore, the build system is not prepared to handle this situation.
