### ISSUE TITLE
DSO-5200 calibrator signal not right

### ISSUE THREAD

**Issue by alaindef** [OpenHantek/openhantek#49]
![openhantek 2017-02-28 15-53-23](https://cloud.githubusercontent.com/assets/9386753/23507960/c0a37a58-ff4f-11e6-872e-fa0afcc3a0ed.png).
testing openhantek ubuntu on DSO-5200.
the display seems to skip pulses when I test the calibrator signal available at the back (see attachment). I guess this is a firmware issue.  I use the dso5200x86-firmware.hex and dso5200x86-loader.hex files I found on this site. 
I want to try extracting the hex files from my working windows 10- 64 bit application, but I can't get the executable for extractfw. I try to compile the extractfw.c file, but got errors "undefined reference to bfd_xxx". I am not experienced in gcc though.
When this firmware issue is solved I 'd like to work on the sw. Can somebody help?

alain.de.feyter@gmail.com

**Comment by davidgraeff** [comment]
Firmware uploading is now part of Openhantek. Would you please test your measurement again?

**Comment by alaindef** [comment]
Thanks for your comment, David. It has been a while since I worked on this subject, but I plan to do new tests mid February.
Alain

**Comment by davidgraeff** [comment]
Closing for now. Please also test the development branch
