### ISSUE TITLE
List of supported devices

### ISSUE THREAD

**Issue by SasQ** [OpenHantek/openhantek#52]
Is there a list of supported devices somewhere? I couldn't find it myself.

**Comment by Pandoriaantje** [comment]
I would assume that if you had a look at the firmware folder of the project, you would be able to tell what devices are supported.

**Comment by SasQ** [comment]
Oh, so _there_ they're hidin' ;)
Nevertheless, it would be nice to link that list somewhere in the readme page.

**Comment by davidgraeff** [comment]
fixed
