### ISSUE TITLE
New name for OpenHantek suggesting that it can be used with other oscilloscopes in the future

### ISSUE THREAD

**Issue by jan-kleks** [OpenHantek/openhantek#56]
Maybe we should think about a new name?

My suggestion:

**OpenScillo**

**Comment by davidgraeff** [comment]
Because of not many people looking after the code at the moment, it is pretty much in maintenance mode only. Sigrok.org can be used for other oscilloscopes.

**Comment by jan-kleks** [comment]
@davidgraeff BTW, would some form of cooperation between you and the Sigrok project possible? Keep up good work!
