### ISSUE TITLE
Unable to install libqt5-dev requirement

### ISSUE THREAD

**Issue by papa-graham** [OpenHantek/openhantek#58]
I have not been able to install this particular requirement using apt-get.
i am on kali linux and i dont know if that is the cause. 
I get this error when i overlook this requirement and try to install.

CMake Error at openhantek2/CMakeLists.txt:3 (add_subdirectory):
  The source directory

    /root/Desktop/pp/openhantek-mr_split_gui_backend/openhantek2/plot

  does not contain a CMakeLists.txt file.

fatal: Needed a single revision
-- Configuring incomplete, errors occurred!
See also "/root/Desktop/pp/openhantek-mr_split_gui_backend/build/CMakeFiles/CMakeOutput.log".
See also "/root/Desktop/pp/openhantek-mr_split_gui_backend/build/CMakeFiles/CMakeError.log".

**Comment by davidgraeff** [comment]
We can't know all different package names on all distributions. We support the two most common ones (debian/ubuntu and fedora). Please find out the correct package name for qt for your distribution.
