### ISSUE TITLE
having trouble with  'make install' ubuntu 16.04

### ISSUE THREAD

**Issue by akharucail** [OpenHantek/openhantek#66]
hi, i am very new to ubuntu and code in general. i have been installing openhantek. i have been following the install instructions. when i type the make install command i get this error response.

cail@AkHaruCailness:~/Downloads/openhantek$ make install
install -m 755 -p "bin/openhantek" "/usr/local/bin/openhantek"
install: cannot create regular file '/usr/local/bin/openhantek': Permission denied
Makefile:558: recipe for target 'install_target' failed
make: [install_target] Error 1 (ignored)
strip "/usr/local/bin/openhantek"
strip: '/usr/local/bin/openhantek': No such file
Makefile:558: recipe for target 'install_target' failed
make: [install_target] Error 1 (ignored)
mkdir: cannot create directory ‘/usr/local/share/apps’: Permission denied
Makefile:568: recipe for target 'install_translations' failed
make: *** [install_translations] Error 1
cail@AkHaruCailness:~/Downloads/openhantek$ 

What am i doing incorrectly?
thanks in advance

**Comment by davidgraeff** [comment]
You don't need to install the application, you can just run the openhantek binding. If you want to install it, use `sudo make install` for administrative rights.
