### ISSUE TITLE
Loading Firmware on OSX?

### ISSUE THREAD

**Issue by tilllt** [OpenHantek/openhantek#68]
Sorry for this simple question, but i cannot find any information on how to load the 6022BE firmware on OSX. Can someone point me in the right direction?
Thanks.

**Comment by tildebyte** [comment]
Build `fxload` from [nexys2-osx](https://github.com/nall/nexys2-osx). I can't really provide support for that.
Once you have `fxload` working
`fxload-osx -t fx2 -D 04b4:6022 -I OpenHantek/openhantek/firmware/dso6022be-firmware.hex -s OpenHantek/openhantek/firmware/dso6022be-loader.hex`
worked for me.
I can't figure out much else yet, but this is my first time using a 'scope...

**Comment by tilllt** [comment]
Thanks!

**Comment by davidgraeff** [comment]
OpenHantek will transfer the firmware now
