### ISSUE TITLE
Threading problems

### ISSUE THREAD

**Issue by ta33ers** [OpenHantek/openhantek#71]
Linux Debian error message:
"QObject: Cannot create children for a parent that is in a different thread.
(Parent is Hantek::Control(0x55649f2b7600), parent's thread is QThread(0x55649f0acfe0), current thread is Hantek::Control(0x55649f2b7600)"

I followed all the instructions, am I missing something? I am having the same problem on Arch Linux, and Debian.

**Comment by davidgraeff** [comment]
OpenHantek was tested with Qt5.1, newer Qt versions might be more restrictive with their thread handling. It is probably not your fault, but at the moment nobody has time to look into this.

**Comment by ta33ers** [comment]
Thanks for your reply, I have got it to work, some what, I hope to try
later with a signal generator.

On Aug 14, 2017 01:02, "David Gräff" <notifications@github.com> wrote:

OpenHantek was tested with Qt5.1, newer Qt versions might be more
restrictive with their thread handling. It is probably not your fault, but
at the moment nobody has time to look into this.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenHantek/openhantek/issues/71#issuecomment-322106698>,
or mute the thread
