### ISSUE TITLE
Datalog mode

### ISSUE THREAD

**Issue by bucklevision** [OpenHantek/openhantek#72]
I can't seem to find a method of using the 6022BE (or others) as a datalogger. I know it's not technically a scope feature but it would potentially be useful for people to be able to say take an average value from a sample every 1s and dump it to CSV with a timestamp and all the hardware is perfectly good for the task. I'll have a dig around the source but can anyone suggest a pointer in the right direction before I start?

**Comment by davidgraeff** [comment]
OpenHantek is in maintenance mode only. We're happy to accept a pull request though. Look at the CSV export as a starting point.
