### ISSUE TITLE
Hantek 1008A support?

### ISSUE THREAD

**Issue by PolynomialDivision** [OpenHantek/openhantek#73]
Hi,
would like to know if the is a plan to support the 1008A device?
Actually I want to develop my own software but there is no SDK for it...
Can somebody give me some tips how to develop with this device?

Thanks.

**Comment by davidgraeff** [comment]
OpenHantek is in maintenance mode. If you want to add 1008A support, you are more than welcome of course :)

**Comment by PolynomialDivision** [comment]
Can you give me some advice how to start? :)

**Comment by davidgraeff** [comment]
I close this for now. We are willing to accept pull requests for more devices. The `hantek/models.h` and `hantek/hantekdsocontrol.h/cpp` files need adaption for a new device.
