### ISSUE TITLE
Running on i3wm causes multiple windows to open.

### ISSUE THREAD

**Issue by JackHunt** [OpenHantek/openhantek#75]
When using the i3 minimal window manager, starting OpenHantek via the terminal opens multiple windows, only one of which actually renders the UI.

In addition, checking some of the math checkboxes will also open windows that appear to render nothing.

My setup is as follows:
Arch Linux
XOrg 1.19.3
i3wm 4.13-1
Linux 4.12.5 x86_64
Qt4 4.8.7-22

Regards

**Comment by JackHunt** [comment]
I can confirm that the issue is also present when building with Qt5 as recommended.

**Comment by davidgraeff** [comment]
This is a won't fix for Qt4. It should work with Qt5. The dock windows need their parent to be set though. If someone has time to look into that, would be very appreciated.
