### ISSUE TITLE
Low resolution display support

### ISSUE THREAD

**Issue by alextrezvy** [OpenHantek/openhantek#85]
Running on a laptop is a cricital function because the device doesn't have the galvanic isolation. It just burns out when measuring power lines. So, is there a way to run with 1024x600 resolution? Now it don't fits on the screen.

**Comment by dendvz** [comment]
Just dock all control windows into tabs and hide toolbars. I have managed to shrink main window to 886x482:
![resize](https://user-images.githubusercontent.com/11679699/33244321-2415816e-d306-11e7-8e10-68562fc620ba.png)

**Comment by davidgraeff** [comment]
I think as well that due to the movable and closeable dock windows, openHantek is very well suited for small resolutions.

**Comment by dendvz** [comment]
@davidgraeff  Hmm, closing the issue completely might be too early. Tabbed layout is not properly saved in settings. Upon restart the tabs are displayed as left-docked.
Composed layout with tabs:
![before](https://user-images.githubusercontent.com/11679699/33291056-aa694082-d3d5-11e7-9592-8a7ee980653e.png)
Turns into:
![after_restart](https://user-images.githubusercontent.com/11679699/33291078-bdd336fa-d3d5-11e7-8993-5995490c68e3.png)

**Comment by davidgraeff** [comment]
Alright, the layout saving is not entirely correct then. That should be fixed of course.
