### ISSUE TITLE
OpenHantek in LabVIEW anyone?

### ISSUE THREAD

**Issue by narra1985** [OpenHantek/openhantek#92]
The LabVIEW SDK provided by Hantek is quite terrible. It would be amazing if a proper oscilloscope and arbitrary waveform generator library could be put together for general use. I have tried to do such a thing but my programming skills are primitive so it's not great. I'm using the 6254BD. Anyone interested to combine effort to produce such a thing?

**Comment by davidgraeff** [comment]
If it's an interface for only one commercial solution, there will be probably not much interest. If you can find a standard protocol that LabVIEW speaks, this might be more interesting.
