### ISSUE TITLE
driver hantek BE series for win 8 or more

### ISSUE THREAD

**Issue by arumrum** [OpenHantek/openhantek#93]
hai, i am currently buying hantek BE series. but i cannot install the driver in windows 8 or more. would you help for this problem?

Thanks in advanced

**Comment by OliverHaag** [comment]
This is not a help forum for the official windows software but a bug tracker for the unofficial primarily linux focused OpenHantek-project, so we can't help with that problem. And even if we could this is definitely the wrong place for asking! Please don't open issues in the tracker unless you've found a bug in OpenHantek.
