### ISSUE TITLE
Build Problem - Linux

### ISSUE THREAD

**Issue by FCPlech** [OpenHantek/openhantek#96]
The "cmake ../" command gets an error, then when I try to use the "make -j" command the OS freezes.

Cmake ../ log:

felipe@felipe-plech ~/Downloads/OpenHantek-openhantek-85aa946/build $ cmake ../
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found libusb: /usr/lib/x86_64-linux-gnu/libusb-1.0.so  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found libfftw3:
--  - Includes: /usr/include
--  - Libraries: /usr/lib/x86_64-linux-gnu/libfftw3.so
-- Configuring done
CMake Error at openhantek/CMakeLists.txt:20 (add_custom_target):
  Cannot find source file:

    .clang-format

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

-- Generating done
-- Build files have been written to: /home/felipe/Downloads/OpenHantek-openhantek-85aa946/build

**Comment by dendvz** [comment]
Should be fixed by PR #98
